### ISSUE TITLE
Upgrade issues from NC 13 -> 14

### ISSUE THREAD

**Issue by ConorIA** [hoellen/dockerfiles#13]
Hi, I'm running your NC 13 image, but when I try to upgrade to NC14-RC2, I get the following error: 

```
server_1  | Checking for update of app activity in appstore
server_1  | An unhandled exception has been thrown:
server_1  | Error: Call to undefined method GuzzleHttp\Client::request() in /nextcloud/lib/private/Http/Client/Client.php:161
server_1  | Stack trace:
server_1  | #0 /nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
server_1  | #1 /nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
server_1  | #2 /nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
server_1  | #3 /nextcloud/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
server_1  | #4 /nextcloud/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('activity')
server_1  | #5 /nextcloud/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
server_1  | #6 /nextcloud/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.18', '13.0.5.2')
server_1  | #7 /nextcloud/core/Command/Upgrade.php(262): OC\Updater->upgrade()
server_1  | #8 /nextcloud/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
server_1  | #9 /nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
server_1  | #10 /nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
server_1  | #11 /nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
server_1  | #12 /nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
server_1  | #13 /nextcloud/console.php(96): OC\Console\Application->run()
server_1  | #14 /nextcloud/occ(11): require_once('/nextcloud/cons...')
```

Have you had a successful 13 -> 14 upgrade? Am I missing something?

P.S. Thanks very much for maintaining these images.

**Comment by ConorIA** [comment]
Nevermind, found it: https://help.nextcloud.com/t/14-0-0-0-rc1-error-after-upgrading/35709/2

**Comment by hoellen** [comment]
I was just looking for this  issues

**Comment by hoellen** [comment]
I was just looking for this issue. And good that you found the fix/problem.
Sorry for reopening I just pushed the wrong button.
